# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vertretungsplan.me
email: info@vertretungsplan.me
description: >
  Mit der kostenlosen Vertretungsplan-App kannst du den Vertretungsplan deiner Schule mit
  Androidâ„¢-Smartphones und -Tablets, iPhones und iPads komfortabel und mit einem tollen Design abrufen.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vertretungsplan.me" # the base hostname & protocol for your site
twitter_username: vplan_app
facebook_username: vertretungsplanme
instagram_username: vplan_app
android_packagename: com.johan.vertretungsplan_2
apple_app_id: 1191463720
matomo_id: 9
exclude:
  - node_modules
  - gulpfile.js
  - less
destination: ../_site/vertretungsplan_me

# Build settings
markdown: kramdown
kramdown:
  toc_levels: 3..6