# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LS Vertretungsplan
email: lornsenschule@vertretungsplan.me
description: >
  Mit der kostenlosen Vertretungsplan-App der Lornsenschule Schleswig kannst du den Vertretungsplan mit
  Androidâ„¢-Smartphones und -Tablets komfortabel und mit einem tollen Design abrufen.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ls.vertretungsplan.me" # the base hostname & protocol for your site
twitter_username: ls_vplan
android_packagename: com.johan.vertretungsplan
windows_phone_url: http://www.windowsphone.com/s?appid=106bf2ea-f1b8-403a-a28e-67a06fee95be
exclude:
  - node_modules
  - gulpfile.js
  - less
destination: ../_site/ls_vertretungsplan_me

# Build settings
markdown: kramdown
kramdown:
  toc_levels: 3..6